[package]
name = "grabchars"
version = "2.0.0-a1"
edition = "2024"
description = "Get keystrokes directly from user - a Rust port of my 1988 Unix utility"
authors = ["Daniel Smith"]
license = "Apache-2.0"

[dependencies]
libc = "0.2"
regex = "1"
